# Product catalogue: fixed price per SKU, as in a real store.
PRODUCTS = [
    {"product": "Wireless Mouse",        "price": 24.99},
    {"product": "Mechanical Keyboard",   "price": 89.50},
    {"product": "USB-C Hub",             "price": 45.00},
    {"product": "Laptop Charger 65W",    "price": 39.95},
    {"product": "HDMI Cable 2m",         "price": 12.75},
    {"product": "Webcam 1080p",          "price": 59.00},
    {"product": "Bluetooth Speaker",     "price": 74.90},
    {"product": "Noise Cancelling Headphones", "price": 199.99},
    {"product": "External SSD 1TB",      "price": 129.00},
    {"product": "Flash Drive 64GB",      "price": 15.50},
    {"product": "Monitor Stand",         "price": 34.25},
    {"product": "Desk Lamp LED",         "price": 28.00},
    {"product": "Power Bank 20000mAh",   "price": 49.99},
    {"product": "Phone Case",            "price": 9.99},
    {"product": "Screen Protector",      "price": 6.50},
    {"product": "Ethernet Cable 5m",     "price": 11.20},
    {"product": "Laptop Sleeve 15in",    "price": 22.40},
    {"product": "Wireless Charger Pad",  "price": 31.75},
    {"product": "Graphics Tablet",       "price": 149.00},
    {"product": "Router AC1200",         "price": 84.60},
    {"product": "Surge Protector",       "price": 19.95},
    {"product": "Cooling Pad",           "price": 27.30},
]